### ISSUE TITLE
Can I ask how to use the SSD structure model?

### ISSUE THREAD

**Issue by yw2278** [clovaai/EXTD_Pytorch#7]
Seems like the demo.py use the FPN structure

**Comment by yw2278** [comment]
Seems like the demo.py use the FPN structure

**Comment by yjyoo3312** [comment]
@yw2278
Yepp, our current version is FPN  (for more accuracy).
You can easily convert our model into SSD like structure by using the source feature maps to 
s1,...., s6 instead of s6,u1....u5 in the EXTD_XX.py files (training required).

**Comment by yw2278** [comment]
OH， I see，Thank you！
