### ISSUE TITLE
What is the purpose of these lines of code?

### ISSUE THREAD

**Issue by kyn0v** [clovaai/EXTD_Pytorch#9]
https://github.com/clovaai/EXTD_Pytorch/blob/e99af10f282d07054c1cf7c4b8c035084daaff78/mobileFacenet_64_PReLU.py#L190-L201

Hello, this conditional statement seems like making no sense. I am not sure that whether the author set it like this deliberately, or there is something wrong with these lines of code.

**Comment by yjyoo3312** [comment]
Ohh Thank you for the comment.
'If cnt >1 else ' statement is useless as you pointed out (same operations work).
It is the trace of the old trials.
We will revise this in the next upcoming large update.

**Comment by kyn0v** [comment]
thank you for your reply, I got it.
